plugins {
  id 'com.android.library'
  id 'expo-module-gradle-plugin'
}

group = 'expo.modules.ritulayawidget'
version = '0.1.0'

android {
  namespace "expo.modules.ritulayawidget"
  compileSdk 35
  defaultConfig {
    minSdk 24
    targetSdk 35
    versionCode 1
    versionName "0.1.0"
  }
  compileOptions {
    sourceCompatibility JavaVersion.VERSION_17
    targetCompatibility JavaVersion.VERSION_17
  }
  kotlinOptions {
    jvmTarget = "17"
  }
}

dependencies {
  implementation "androidx.core:core-ktx:1.15.0"
}
